version: "3.9"

services:
  mysql:
    image: mysql:8.4          # 使用官方 8.x 最新镜像
    container_name: chat-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root123456        # ⚠️ 改成强密码
      MYSQL_DATABASE: chat_ai              # 启动即创建数据库
      MYSQL_USER: chat_user                # 专用业务账号
      MYSQL_PASSWORD: 123456             # 专用业务密码

    ports:
      - "3333:3306"

    volumes:
      - ./mysql-data:/var/lib/mysql        # 数据持久化
      - ./init-sql:/docker-entrypoint-initdb.d
      # ↳ 把建表脚本放这里，容器首启自动执行




  redis:
    image: redis:7.2
    container_name: chat-redis
    restart: always
    ports:
      - "6333:6379"
    command: [ "redis-server", "--appendonly", "yes" ]   # AOF 持久化
